- name: start ovs
  service:
    name: openvswitch
    state: started

- name: set dpdk-socket-mem
  command: "ovs-vsctl --no-wait set open_vswitch . other_config:dpdk-socket-mem=\"1024,\""

- name: set dpdk-init
  openvswitch_db:
    table: open_vswitch
    record: .
    col: other_config
    key: dpdk-init
    timeout: 60
    value: true
