- name: install packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
  - pciutils
  - dpdk
  - dpdk-tools
  - driverctl
  - tuned-profiles-cpu-partitioning
  - openvswitch

- name: configure kernel
  configure_kernel:
    pci_addresses: "{{ pci_addresses }}"
  register: configure_kernel

- set_fact:
    cpu_list: "{{ configure_kernel.cpu_list }}"

- name: restart server
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  become: true
  ignore_errors: true
  when: configure_kernel.changed

- name: allow host to restart before proceeding
  pause: seconds=2
  when: configure_kernel.changed

- name: Wait for host to come back
  wait_for_connection:
    timeout: 600

- name: set vfio permissions 1
  command: /usr/bin/chmod a+x /dev/vfio

- name: set vfio permissions 2
  command: /usr/bin/chmod 0666 /dev/vfio/*


